---
title: "git_00"
author: "Rachel Gilpatrick"
date: "09 Sept. 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  

“Beware the Jabberwock, my son!

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,  
Some say in ice.  
From what I’ve tasted of desire  
I hold with those who favor fire.  
But if it had to perish twice,

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

They always followed you.  

Disdainful dogs,  
they made you lose your balance.  

You had to shout  
blasphemies into shadows  
trying to put out the din of their barking.  

Other times  
it was advisable to talk and try to calm them,  
whispers could be more convincing  
and stop them on any corner,  
so as to continue alone.  

Solitude is a walk through the streets of Baltimore.  

You could never free yourself,  
those shadows were growing,  
crows perched on the statues  
with eyes fixed on the emptiness of a demon who dreams.  

To you,  
who were on the edge of a dismal midnight  
watching specters of dying embers on the ground.  

To you,  
who tasted sorrow,  
who drank it like an exquisite liqueur,  
I come close  
and I look at you trying to find you on the other side of the stone  
carved by misfortune,  
the same as happens with beauty.  

Never again will the silver bells ring,  
the ships that now arrive at the port of Baltimore  
are filled with people too frightened to speak.  

They bring a stone in place of the heart,  
they do not sense these shadows that wander the streets,  
these shadows that are neither men nor women nor beasts,  
perhaps dogs or birds or words in the beaks of the birds  
or in their jaws.  

When they pass they are nothing more than the sea breeze  
from which they come.  

There is a silence now  
about silence  
in the shadows.  

They bite like words 
in place of the heart.  
